### ISSUE TITLE
Verify User Is Running Windows 10 And PowerShell 5.0

### ISSUE THREAD

**Issue by war59312** [hulr/BetterPrivacy#1]
Hey,

It may sound stupid, but users are idiots. ;)

You should verify the user is running on Windows 10 and running in PowerShell 5.0.

Thanks,

Will

**Comment by hulr** [comment]
You're right, I missed that. Fixed with commit [40ffc41](https://github.com/hulr/BetterPrivacy/commit/40ffc413f32fec448461df3bff5a8bf578a1d846)

**Comment by war59312** [comment]
That does NOT seem to ever run here.

Tested on Win8.1. Simply run "run.cmd". Asks for admins rights as expected via uac. Then shows UI. No msg about not being supported.

If I just click run I get:

> [19:34:30] start
> [19:34:30] you have not configured any services to disable
> [19:34:30] you have not configured any apps to remove
> [19:34:30] you have not configured any domains to block
> [19:34:30] you have not configured any ips to block
> [19:34:30] you have not configured any general telemetry settings to change
> [19:34:30] end, log file created @ C:\Users\Username\Downloads\BetterPrivacy-master\BetterPrivacy.log

Think it would be more wise to check at the start of script.

**Comment by hulr** [comment]
Did you really download the latest files? I set up a Windows 8.1 test machine and it worked out fine.

**Comment by war59312** [comment]
Ok your right, I had downloaded master zip. POS.

Anyhow, that works but perhaps better to check at start of script and tell user right at the start.

No point in loading ui and asking for admin rights via uac when not on Win10.

**Comment by hulr** [comment]
I hope your are satisfied with the latest change: [779d626](https://github.com/hulr/BetterPrivacy/commit/779d6261db38e91b32e4a1533a4b2622224c112f) :smile:

**Comment by war59312** [comment]
Better, thanks.

I'd check OS and Powershell version within the powershell script itself.

Something like:

```
function CheckPowerShellVersion {

    #
    #   === Checks If PowerShell Version 5.0 Is Installed ===
    #

    $hostVersionInfo = (get-host).Version.Major
    if ( $hostVersionInfo -ne "5" )
    {
        write "This Computer Has PowerShell Version $hostVersionInfo... You MUST Have PowerShell Version 5.0!"
        exit
    }
    else
    {
        write-host "Unknown Version Of PowerShell. You MUST Have Powershell Version 5.0!"
        exit
    }

    # Script Ends Here
    Return

}
```

Also, nice smiley. hehe

**Comment by hulr** [comment]
This is not needed because PowerShell 5 is on every Windows 10 version out of the box. It's sufficient if I check for the OS version in the PowerShell script and the Batch file.

**Comment by war59312** [comment]
That's right. CRS sometimes. ;)
