### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by W4RH4WK** [hulr/BetterPrivacy#2]
Hiho, I saw a link to your repo in @10se1ucgo 's project.

I created a similar project a few months ago, also in PowerShell, but without GUI and targeted at server admins. You may want to check out the code, maybe you find something to extend your project.

https://github.com/W4RH4WK/Debloat-Windows-10

Don't hesitate to open a pull-request / issue if you find a mistake or have relevant improvements.

**Comment by TheNain38** [comment]
@W4RH4WK He already thanked you for your "Debloat-Windows-10" if you look in the README

**Comment by hulr** [comment]
Thanks for your message. I wil for sure check out your repo in the future.

**Comment by W4RH4WK** [comment]
Oh yeah, thanks ^^
