### ISSUE TITLE
FYI: Another tool with the same name

### ISSUE THREAD

**Issue by Gitoffthelawn** [hulr/BetterPrivacy#3]
Just so you know, there is a popular and well-known Firefox extension with over a half-million users that has the same name.

See https://addons.mozilla.org/firefox/addon/betterprivacy/

It's a Firefox extension, and your tool is a Windows 10 PowerShell script, so they are obviously different things, but I thought you might appreciate being aware that there is another tool with the same name.

**Comment by hulr** [comment]
Ok, didn't know that. Thanks.
